"""Observation

Revision ID: 1a4019cadd38
Revises: 
Create Date: 2024-01-04 21:57:49.750776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4019cadd38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observation_value',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('observation_element_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.LargeBinary(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['observation_element_id'], ['meteor_core.observation_element.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['meteor_core.organization.id'], ),
    sa.PrimaryKeyConstraint('id', 'organization_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation_value')
    # ### end Alembic commands ###
