"""Observation

Revision ID: c27282e4bb80
Revises: e8d36673ee98
Create Date: 2024-01-04 21:57:49.510387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c27282e4bb80'
down_revision: Union[str, None] = 'e8d36673ee98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings_entity',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1023), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='meteor_core'
    )
    op.create_table('observation_element',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='meteor_core'
    )
    op.drop_constraint('meteor_user_organization_meteor_user_id_fkey', 'meteor_user_organization', type_='foreignkey')
    op.drop_constraint('meteor_user_organization_organization_id_fkey', 'meteor_user_organization', type_='foreignkey')
    op.create_foreign_key(None, 'meteor_user_organization', 'organization', ['organization_id'], ['id'], source_schema='meteor_core', referent_schema='meteor_core')
    op.create_foreign_key(None, 'meteor_user_organization', 'meteor_user', ['meteor_user_id'], ['id'], source_schema='meteor_core', referent_schema='meteor_core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meteor_user_organization', schema='meteor_core', type_='foreignkey')
    op.drop_constraint(None, 'meteor_user_organization', schema='meteor_core', type_='foreignkey')
    op.create_foreign_key('meteor_user_organization_organization_id_fkey', 'meteor_user_organization', 'organization', ['organization_id'], ['id'])
    op.create_foreign_key('meteor_user_organization_meteor_user_id_fkey', 'meteor_user_organization', 'meteor_user', ['meteor_user_id'], ['id'])
    op.drop_table('observation_element', schema='meteor_core')
    op.drop_table('app_settings_entity', schema='meteor_core')
    # ### end Alembic commands ###
