"""Changes

Revision ID: e8d36673ee98
Revises: 
Create Date: 2024-01-01 18:45:45.829464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8d36673ee98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meteor_user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('last_mfa_time', sa.DateTime(), nullable=True),
    sa.Column('experimental_features', sa.Boolean(), nullable=True),
    sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='meteor_core'
    )
    op.create_index('meteor_user_search_vector_idx', 'meteor_user', ['search_vector'], unique=False, schema='meteor_core', postgresql_using='gin')
    op.create_table('meteor_user_organization',
    sa.Column('meteor_user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meteor_user_id'], ['meteor_core.meteor_user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['meteor_core.organization.id'], ),
    sa.PrimaryKeyConstraint('meteor_user_id', 'organization_id'),
    schema='meteor_core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meteor_user_organization', schema='meteor_core')
    op.drop_index('meteor_user_search_vector_idx', table_name='meteor_user', schema='meteor_core', postgresql_using='gin')
    op.drop_table('meteor_user', schema='meteor_core')
    # ### end Alembic commands ###
