"""Initial_Revision

Revision ID: 4f23fe5f7582
Revises: 
Create Date: 2023-12-31 23:14:24.120369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f23fe5f7582'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('organization_search_vector_idx', table_name='organization', schema='meteor_core', postgresql_using='gin')
    op.drop_table('organization', schema='meteor_core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('meteor_core.organization_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('banner_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('banner_color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('banner_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='organization_pkey'),
    sa.UniqueConstraint('name', name='organization_name_key'),
    schema='meteor_core'
    )
    op.create_index('organization_search_vector_idx', 'organization', ['search_vector'], unique=False, schema='meteor_core', postgresql_using='gin')
    # ### end Alembic commands ###
